site_name: Bixing's Notebook
site_author: Wu Bixing
site_url: https://wbx0710.github.io/mymkdocs/
repo_url: https://github.com/Wbx0710/mymkdocs
repo_name: Bixing's Repositories
use_directory_urls: false

nav:
  - 首页: index.md
  - 大二春夏:
      - 课程概览: SophomoreSpringSummer/Courses/index.md
      - 信号与系统:
          - 课程指北: SophomoreSpringSummer/SignalsSystems/CourseOverview/index.md
          - Notes:
              - 基本概念: SophomoreSpringSummer/SignalsSystems/Notes/Chapter1/index.md
              - LTI: SophomoreSpringSummer/SignalsSystems/Notes/Chapter2/index.md
      - 数字系统设计:
          - 课程指北: SophomoreSpringSummer/DigitalSystem/CourseOverview/index.md
          - Notes:
              - 概述: SophomoreSpringSummer/DigitalSystem/DigitalSystemNotes/index.md
              - 逻辑代数与化简: SophomoreSpringSummer/DigitalSystem/DigitalSystemNotes/Chapter1/index.md
              - TTL&CMOS: SophomoreSpringSummer/DigitalSystem/DigitalSystemNotes/Chapter2/index.md
              - 加法器: SophomoreSpringSummer/DigitalSystem/DigitalSystemNotes/Chapter3/index.md
              - 编码器&译码器: SophomoreSpringSummer/DigitalSystem/DigitalSystemNotes/Chapter4/index.md
              - 触发器: SophomoreSpringSummer/DigitalSystem/DigitalSystemNotes/Chapter5/index.md
              - 时序分析&设计: SophomoreSpringSummer/DigitalSystem/DigitalSystemNotes/Chapter6/index.md
              - 计数器&寄存器: SophomoreSpringSummer/DigitalSystem/DigitalSystemNotes/Chapter7/index.md
      - 半导体物理:
          - 课程指北: SophomoreSpringSummer/SemiconductorPhysics/CourseOverview/index.md
      - 马克思主义基本原理:
          - 课程指北: SophomoreSpringSummer/Marxism/CourseOverview/index.md
          - Notes: SophomoreSpringSummer/Marxism/MyNotes/index.md
      - 数据结构基础:
          - 课程指北: SophomoreSpringSummer/FDS/CourseOverview/index.md
      - 信息理论:
          - 课程指北: SophomoreSpringSummer/InformationTheory/CourseOverview/index.md
      - 人工智能前沿:
          - 课程指北: SophomoreSpringSummer/AIFrontiers/CourseOverview/index.md
      - 控制的哲学与方法:
          - 课程指北: SophomoreSpringSummer/PhilosophyofControl/CourseOverview/index.md
      - 电子电路设计实验II:
          - 课程指北: SophomoreSpringSummer/ElectronicCircuitDesign/CourseOverview/index.md
      - 数字系统设计实验:
          - 课程指北: SophomoreSpringSummer/DigitalSystemExperiment/CourseOverview/index.md
          - Verilog:
              - Verilog基础知识: SophomoreSpringSummer/DigitalSystemExperiment/Verilog/index.md
      - 通识课专栏:
          - 课程指北: SophomoreSpringSummer/GeneralEducation/CourseOverview/index.md
          - 法知历年题: SophomoreSpringSummer/GeneralEducation/FrenchIntellectuals/index.md
  - 大二秋冬:
      - 课程概览: SophomoreFallWinter/Courses/index.md
      - 电子电路基础:
          - 课程指北: SophomoreFallWinter/BasicElectronicCircuits/CourseOverview/index.md
          - 电子电路基础习题集萃: SophomoreFallWinter/BasicElectronicCircuits/Exercise/index.md
      - 大学物理甲II:
          - 课程指北: SophomoreFallWinter/Physics/CourseOverview/index.md
          - MyNotes:
              - PDF版汇总下载: SophomoreFallWinter/Physics/MyNotes/index.md
              - Chapter9: SophomoreFallWinter/Physics/MyNotes/chapter9/index.md
              - Chapter10: SophomoreFallWinter/Physics/MyNotes/chapter10/index.md
              - Chapter11: SophomoreFallWinter/Physics/MyNotes/chapter11/index.md
              - Chapter12: SophomoreFallWinter/Physics/MyNotes/chapter12/index.md
              - Chapter13: SophomoreFallWinter/Physics/MyNotes/chapter13/index.md
              - Chapter14: SophomoreFallWinter/Physics/MyNotes/chapter14/index.md
              - Chapter15: SophomoreFallWinter/Physics/MyNotes/chapter15/index.md
              - Chapter16: SophomoreFallWinter/Physics/MyNotes/chapter16/index.md
              - Chapter17: SophomoreFallWinter/Physics/MyNotes/chapter17/index.md
              - Chapter18: SophomoreFallWinter/Physics/MyNotes/chapter18/index.md
              - Chapter19: SophomoreFallWinter/Physics/MyNotes/chapter19/index.md
              - Chapter20: SophomoreFallWinter/Physics/MyNotes/chapter20/index.md
              - Chapter21: SophomoreFallWinter/Physics/MyNotes/chapter21/index.md
              - Chapter22: SophomoreFallWinter/Physics/MyNotes/chapter22/index.md
              - Chapter23: SophomoreFallWinter/Physics/MyNotes/chapter23/index.md
          - 期中试卷: SophomoreFallWinter/Physics/Interim/index.md
          - 期末试卷: SophomoreFallWinter/Physics/Final/index.md
      - 数学建模:
          - 课程指北: SophomoreFallWinter/MathematicalModeling/CourseOverview/index.md
      - 固体物理基础:
          - 课程指北: SophomoreFallWinter/SolidStatePhysics/CourseOverview/index.md
          - 复习资料: SophomoreFallWinter/SolidStatePhysics/Review/index.md
      - 概率论与数理统计:
          - 课程指北: SophomoreFallWinter/Probability/CourseOverview/index.md
          - MyNotes:
              - MyNotes: SophomoreFallWinter/Probability/MyNotes/index.md
              - Chapter1: SophomoreFallWinter/Probability/MyNotes/Chapter1/index.md
              - Chapter2: SophomoreFallWinter/Probability/MyNotes/Chapter2/index.md
          - 概统PPT:
              - 概统PPT: SophomoreFallWinter/Probability/PPT/index.md
              - Chapter1: SophomoreFallWinter/Probability/PPT/chapter1/index.md
              - Chapter2: SophomoreFallWinter/Probability/PPT/chapter2/index.md
              - Chapter3: SophomoreFallWinter/Probability/PPT/chapter3/index.md
              - Chapter4: SophomoreFallWinter/Probability/PPT/chapter4/index.md
              - Chapter5: SophomoreFallWinter/Probability/PPT/chapter5/index.md
              - Chapter6: SophomoreFallWinter/Probability/PPT/chapter6/index.md
              - Chapter7: SophomoreFallWinter/Probability/PPT/chapter7/index.md
          - 知识点整理: SophomoreFallWinter/Probability/Collate/index.md
      - 数值分析方法:
          - 课程指北: SophomoreFallWinter/NumericalAnalysis/CourseOverview/index.md
          - 知识图谱: SophomoreFallWinter/NumericalAnalysis/KnowledgeMap/index.md
          - 知识整理: SophomoreFallWinter/NumericalAnalysis/Review/index.md
      - 复变函数与积分变换:
          - 课程指北: SophomoreFallWinter/ComplexFunctions/CourseOverview/index.md
          - MyNotes:
              - MyNotes: SophomoreFallWinter/ComplexFunctions/MyNotes/index.md
              - Chapter1: SophomoreFallWinter/ComplexFunctions/MyNotes/Chapter1/index.md
              - Chapter2: SophomoreFallWinter/ComplexFunctions/MyNotes/Chapter2/index.md
              - Chapter3: SophomoreFallWinter/ComplexFunctions/MyNotes/Chapter3/index.md
              - Chapter4: SophomoreFallWinter/ComplexFunctions/MyNotes/Chapter4/index.md
          - 杨海涛老师的PPT: SophomoreFallWinter/ComplexFunctions/PPT/index.md
      - 大学物理实验:
          - 课程指北: SophomoreFallWinter/PhysicalExperiment/CourseOverview/index.md
          - 实验报告: SophomoreFallWinter/PhysicalExperiment/LabReport/index.md
      - 工程训练:
          - 课程指北: SophomoreFallWinter/EngineeringTraining/CourseOverview/index.md
          - MyNotes: SophomoreFallWinter/EngineeringTraining/MyNotes/index.md
          - 工训题库: SophomoreFallWinter/EngineeringTraining/QuestionBank/index.md
      - 工程导论:
          - 课程指北: SophomoreFallWinter/IntroductiontoEngineering/CourseOverview/index.md
      - 电子电路设计实验I:
          - 课程指北: SophomoreFallWinter/ElectronicCircuitDesign/CourseOverview/index.md
      - 通识课专栏:
          - 课程指北: SophomoreFallWinter/GeneralEducation/CourseOverview/index.md
  - 收藏页:
      - 收藏的网页: Favorites/FavoritePages/index.md

theme:
  name: material

  repo_url: https://github.com/Wbx0710/mymkdocs
  repo_name: Bixing's Repositories

  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式

  features:
    - navigation.tracking # 在url中使用标题定位锚点
    - navigation.path # 显示当前路径
    - navigation.prune # 侧边栏自动折叠
    - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
    - navigation.indexes # 指定节点index pages ，跟instant不兼容
    - navigation.top # 一键回顶部
    - navigation.footer # 底部导航
    - search.highlight # 搜索高亮
    - search.suggest # 搜索建议
    - toc.follow # toc 跟随
    - content.code.annotate # 代码行号
    - content.code.copy # 代码复制

  language: "zh"
  icon:
    previous: fontawesome/solid/angle-left # 左下角向前翻页的图标
    next: fontawesome/solid/angle-right # 右下角向后翻页的图标
    repo: fontawesome/brands/github # 右上角仓库图标
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  logo: images/logo.jpg
  favicon: images/logo.jpg

plugins:
  - glightbox
  - tags
  #- heti:
  #disable_serve: false
  - statistics:
      words_per_minute: 200
  - search:
      lang:
        - zh
        - en
        - ja
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: false

copyright: Copyright &copy; 2023~2025 WuBixing/All Rights Reserved. # 左下角的版权声明

extra_css:
  - assets/stylesheets/clock.css
  - assets/stylesheets/extra.css
  - assets/stylesheets/glightbox.min.css
  - assets/stylesheets/charging.css
  - assets/stylesheets/card.css
  - assets/stylesheets/tony.css
  - assets/stylesheets/flink.css
  - assets/stylesheets/neoteroi-mkdocs.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

extra_javascript:
  - assets/javascripts/katex.js
  - assets/javascripts/clock.js
  - assets/javascripts/mathjax.js
  - assets/javascripts/document.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascripts/titlechange.js
  - assets/javascripts/glightbox.min.js
  - assets/javascripts/click.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Wbx0710
      name: Bixing's Notebook
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/442107458/favlist?fid=2473170958&ftype=create
      name: Bilibili

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - tables
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 5
      permalink_title: 点击此处可置顶内容
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
