site_name: Bixing's Notebook
site_author: 吴必兴
site_url: https://wbx0710.github.io/mymkdocs/
repo_url: https://github.com/Wbx0710/mymkdocs
repo_name: Bixing's Repositories
use_directory_urls: false

nav:
  - 首页: index.md
  - 大二春夏:
      - 课程概览: 大二春夏/课程概览/index.md
      - 信号与系统: 
          - 课程指北: 大二春夏/信号与系统/课程指北/index.md
      - 数字系统设计: 
          - 课程指北: 大二春夏/数字系统设计/课程指北/index.md
      - 半导体物理: 
          - 课程指北: 大二春夏/半导体物理/课程指北/index.md
      - 马克思主义基本原理: 
          - 课程指北: 大二春夏/马克思主义基本原理/课程指北/index.md
      - 数据结构基础: 
          - 课程指北: 大二春夏/数据结构基础/课程指北/index.md
      - 信息理论: 
          - 课程指北: 大二春夏/信息理论/课程指北/index.md
      - 人工智能前沿: 
          - 课程指北: 大二春夏/人工智能前沿/课程指北/index.md
      - 控制的哲学与方法: 
          - 课程指北: 大二春夏/控制的哲学与方法/课程指北/index.md
      - 电子电路设计实验II: 
          - 课程指北: 大二春夏/电子电路设计实验/课程指北/index.md
      - 数字系统设计实验: 
          - 课程指北: 大二春夏/数字系统设计实验/课程指北/index.md
      - 通识课专栏: 
          - 课程指北: 大二春夏/通识课专栏/课程指北/index.md
  - 大二秋冬: 
      - 课程概览: 大二秋冬/课程概览/index.md
      - 电子电路基础: 
          - 课程指北: 大二秋冬/电子电路基础/课程指北/index.md
          - 电子电路基础习题集萃: 大二秋冬/电子电路基础/电基习题集萃/index.md
      - 大学物理甲II: 
          - 课程指北: 大二秋冬/大学物理甲II/课程指北/index.md
          - MyNotes: 
            - PDF版汇总下载: 大二秋冬/大学物理甲II/MyNotes/index.md
            - Chapter9: 大二秋冬/大学物理甲II/MyNotes/chapter9/index.md
            - Chapter10: 大二秋冬/大学物理甲II/MyNotes/chapter10/index.md
            - Chapter11: 大二秋冬/大学物理甲II/MyNotes/chapter11/index.md
            - Chapter12: 大二秋冬/大学物理甲II/MyNotes/chapter12/index.md
            - Chapter13: 大二秋冬/大学物理甲II/MyNotes/chapter13/index.md
            - Chapter14: 大二秋冬/大学物理甲II/MyNotes/chapter14/index.md
            - Chapter15: 大二秋冬/大学物理甲II/MyNotes/chapter15/index.md
            - Chapter16: 大二秋冬/大学物理甲II/MyNotes/chapter16/index.md
            - Chapter17: 大二秋冬/大学物理甲II/MyNotes/chapter17/index.md
            - Chapter18: 大二秋冬/大学物理甲II/MyNotes/chapter18/index.md
            - Chapter19: 大二秋冬/大学物理甲II/MyNotes/chapter19/index.md
            - Chapter20: 大二秋冬/大学物理甲II/MyNotes/chapter20/index.md
            - Chapter21: 大二秋冬/大学物理甲II/MyNotes/chapter21/index.md
            - Chapter22: 大二秋冬/大学物理甲II/MyNotes/chapter22/index.md
            - Chapter23: 大二秋冬/大学物理甲II/MyNotes/chapter23/index.md
      - 数学建模:
          - 课程指北: 大二秋冬/数学建模/课程指北/index.md
      - 固体物理基础:
          - 课程指北: 大二秋冬/固体物理基础/课程指北/index.md
          - 回忆卷: 大二秋冬/固体物理基础/回忆卷/index.md
      - 概率论与数理统计:
          - 课程指北: 大二秋冬/概率论与数理统计/课程指北/index.md
          - MyNotes: 
            - MyNotes: 大二秋冬/概率论与数理统计/MyNotes/index.md
            - Chapter1: 大二秋冬/概率论与数理统计/MyNotes/Chapter1/index.md
            - Chapter2: 大二秋冬/概率论与数理统计/MyNotes/Chapter2/index.md
          - 概统PPT: 
            - 概统PPT: 大二秋冬/概率论与数理统计/概统PPT/index.md
            - Chapter1: 大二秋冬/概率论与数理统计/概统PPT/chapter1/index.md
            - Chapter2: 大二秋冬/概率论与数理统计/概统PPT/chapter2/index.md
            - Chapter3: 大二秋冬/概率论与数理统计/概统PPT/chapter3/index.md
            - Chapter4: 大二秋冬/概率论与数理统计/概统PPT/chapter4/index.md
            - Chapter5: 大二秋冬/概率论与数理统计/概统PPT/chapter5/index.md
            - Chapter6: 大二秋冬/概率论与数理统计/概统PPT/chapter6/index.md
            - Chapter7: 大二秋冬/概率论与数理统计/概统PPT/chapter7/index.md
          - 知识点整理: 大二秋冬/概率论与数理统计/知识点整理/index.md
      - 数值分析方法: 
          - 课程指北: 大二秋冬/数值分析方法/课程指北/index.md
          - 知识图谱: 大二秋冬/数值分析方法/知识图谱/index.md
          - 知识整理: 大二秋冬/数值分析方法/知识整理/index.md
      - 复变函数与积分变换: 
          - 课程指北: 大二秋冬/复变函数与积分变换/课程指北/index.md
          - MyNotes: 
            - MyNotes: 大二秋冬/复变函数与积分变换/MyNotes/index.md
            - Chapter1: 大二秋冬/复变函数与积分变换/MyNotes/Chapter1/index.md
            - Chapter2: 大二秋冬/复变函数与积分变换/MyNotes/Chapter2/index.md
            - Chapter3: 大二秋冬/复变函数与积分变换/MyNotes/Chapter3/index.md
            - Chapter4: 大二秋冬/复变函数与积分变换/MyNotes/Chapter4/index.md
          - 杨海涛老师的PPT: 大二秋冬/复变函数与积分变换/PPT/index.md
      - 大学物理实验: 
          - 课程指北: 大二秋冬/大学物理实验/课程指北/index.md
          - 实验报告: 大二秋冬/大学物理实验/实验报告/index.md
      - 工程训练: 
          - 课程指北: 大二秋冬/工程训练/课程指北/index.md
          - 工训题库: 大二秋冬/工程训练/工训题库/index.md
      - 工程导论: 
          - 课程指北: 大二秋冬/工程导论/课程指北/index.md
      - 电子电路设计实验I: 
          - 课程指北: 大二秋冬/电设实验I/课程指北/index.md
      - 通识课专栏: 
          - 课程指北: 大二秋冬/通识课/课程指北/index.md
  - 无限进步: 
      - 简介: 无限进步/简介/index.md
      - Jetson Nano: 无限进步/Jetson/index.md
  - Bixing's 收藏页: 
      - 收藏的网页: Bixing's 收藏页/收藏的网页/index.md
      - MyCC98: Bixing's 收藏页/CC98/index.md
      - 时间管理: Bixing's 收藏页/时间管理/index.md
      - 用随机梯度下降来优化人生: Bixing's 收藏页/李沐大佬/index.md


theme:
  name: material
  
  repo_url: https://github.com/Wbx0710/mymkdocs
  repo_name: Bixing's Repositories

  palette: 
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent:  teal
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式

  features:
    - navigation.tracking # 在url中使用标题定位锚点
    - navigation.path # 显示当前路径
    - navigation.prune # 侧边栏自动折叠
    - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
    - navigation.indexes # 指定节点index pages ，跟instant不兼容
    - navigation.top # 一键回顶部
    - navigation.footer # 底部导航
    - search.highlight # 搜索高亮
    - search.suggest # 搜索建议
    - toc.follow # toc 跟随
    - content.code.annotate # 代码行号
    - content.code.copy # 代码复制

  language: 'zh'
  icon:
    previous: fontawesome/solid/angle-left # 左下角向前翻页的图标
    next: fontawesome/solid/angle-right # 右下角向后翻页的图标
    repo: fontawesome/brands/github # 右上角仓库图标
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  logo: images/logo.jpg
  favicon: images/logo.jpg

plugins:
  - glightbox
  - tags
  #- heti:
      #disable_serve: false
  - statistics:
      words_per_minute: 300
  - search:
      lang:
        - zh
        - en
        - ja
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: false

copyright: Copyright &copy; 2023~2024 WuBixing/All Rights Reserved. # 左下角的版权声明

extra_css:
  - assets/stylesheets/clock.css
  - assets/stylesheets/extra.css
  - assets/stylesheets/glightbox.min.css
  - assets/stylesheets/charging.css
  - assets/stylesheets/card.css
  - assets/stylesheets/tony.css
  - assets/stylesheets/flink.css
  - assets/stylesheets/neoteroi-mkdocs.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

extra_javascript:
  - assets/javascripts/katex.js
  - assets/javascripts/clock.js
  - assets/javascripts/mathjax.js
  - assets/javascripts/document.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascripts/titlechange.js
  - assets/javascripts/glightbox.min.js
  - assets/javascripts/click.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Wbx0710
      name: Bixing's Notebook
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/442107458/favlist?fid=2473170958&ftype=create
      name: Bilibili

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - tables
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 5
      permalink_title: 点击此处可置顶内容
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
